Load Julia packages (libraries) needed  for the snippets in chapter 0

In [1]:
using DynamicHMCModels

### snippet 10.4

In [2]:
d = CSV.read(rel_path("..", "data", "chimpanzees.csv"), delim=';');
df = convert(DataFrame, d);
df[!, :pulled_left] = convert(Array{Int64}, df[!, :pulled_left])
df[!, :prosoc_left] = convert(Array{Int64}, df[!, :prosoc_left])
first(df, 5)

struct m_10_02d_model{TY <: AbstractVector, TX <: AbstractMatrix}
    "Observations."
    y::TY
    "Covariates"
    X::TX
    "Number of observations"
    N::Int
end

Make the type callable with the parameters *as a single argument*.

In [3]:
function (problem::m_10_02d_model)(θ)
    @unpack y, X, N = problem   # extract the data
    @unpack β = θ  # works on the named tuple too
    ll = 0.0
    ll += sum(logpdf.(Normal(0, 10), β)) # a & bp
    ll += sum([loglikelihood(Binomial(1, logistic(dot(X[i, :], β))), [y[i]]) for i in 1:N])
    ll
end

Instantiate the model with data and inits.

In [4]:
N = size(df, 1)
X = hcat(ones(Int64, N), df[!, :prosoc_left]);
y = df[!, :pulled_left]
p = m_10_02d_model(y, X, N);
θ = (β = [1.0, 2.0],)
p(θ)

-487.6540051035728

Write a function to return properly dimensioned transformation.

In [5]:
problem_transformation(p::m_10_02d_model) =
  as( (β = as(Array, size(p.X, 2)), ) )

problem_transformation (generic function with 1 method)

Wrap the problem with a transformation, then use Flux for the gradient.

In [6]:
P = TransformedLogDensity(problem_transformation(p), p)
∇P = LogDensityRejectErrors(ADgradient(:ForwardDiff, P));
#∇P = ADgradient(:ForwardDiff, P);

Tune and sample.

In [7]:
chain, NUTS_tuned = NUTS_init_tune_mcmc(∇P, 1000);

MCMC, adapting ϵ (75 steps)
0.00081 s/step ...done
MCMC, adapting ϵ (25 steps)
0.0026 s/step ...done
MCMC, adapting ϵ (50 steps)
0.00092 s/step ...done
MCMC, adapting ϵ (100 steps)
0.0011 s/step ...done
MCMC, adapting ϵ (200 steps)
0.0008 s/step ...done
MCMC, adapting ϵ (400 steps)
0.00071 s/step ...done
MCMC, adapting ϵ (50 steps)
0.00081 s/step ...done
MCMC (1000 steps)
step 745 (of 1000), 0.0013 s/step
0.0013 s/step ...done


We use the transformation to obtain the posterior from the chain.

In [8]:
posterior = TransformVariables.transform.(Ref(problem_transformation(p)), get_position.(chain));
posterior[1:5]

5-element Array{NamedTuple{(:β,),Tuple{Array{Float64,1}}},1}:
 (β = [-0.07232668404758982, 0.6630660027432933],) 
 (β = [0.03395437083680505, 0.46149069265519904],) 
 (β = [-0.11142520555697846, 0.7423387845235908],) 
 (β = [-0.08678340945244874, 0.714957443141185],)  
 (β = [0.0038315467573788176, 0.5810986141301616],)

Extract the parameter posterior means: `β`,

In [9]:
posterior_β = mean(first, posterior)

2-element Array{Float64,1}:
 0.04453749249125186
 0.5628544133500475 

Effective sample sizes (of untransformed draws)

In [10]:
ess = mapslices(effective_sample_size, get_position_matrix(chain); dims = 1)
ess

1×2 Array{Float64,2}:
 723.943  611.152

NUTS-specific statistics

In [11]:
NUTS_statistics(chain)

Hamiltonian Monte Carlo sample of length 1000
  acceptance rate mean: 0.93, min/25%/median/75%/max: 0.51 0.89 0.96 1.0 1.0
  termination: AdjacentTurn => 35% DoubledTurn => 65%
  depth: 1 => 16% 2 => 60% 3 => 13% 4 => 6% 5 => 5% 6 => 0%


CmdStan result

In [12]:
m_10_2s_result = "
Iterations = 1:1000
Thinning interval = 1
Chains = 1,2,3,4
Samples per chain = 1000

Empirical Posterior Estimates:
      Mean        SD       Naive SE       MCSE      ESS
 a 0.05103234 0.12579086 0.0019889282 0.0035186307 1000
bp 0.55711212 0.18074275 0.0028577937 0.0040160451 1000

Quantiles:
       2.5%        25.0%       50.0%      75.0%      97.5%
 a -0.19755400 -0.029431425 0.05024655 0.12978825 0.30087758
bp  0.20803447  0.433720250 0.55340400 0.67960975 0.91466915
";

Extract the parameter posterior means: `β`,

In [13]:
posterior_β = mean(first, posterior)

2-element Array{Float64,1}:
 0.04453749249125186
 0.5628544133500475 

End of `10/m10.02d.jl`

*This notebook was generated using [Literate.jl](https://github.com/fredrikekre/Literate.jl).*