Load Julia packages (libraries) needed  for the snippets in chapter 0

In [1]:
using DynamicHMCModels

CmdStan uses a tmp directory to store the output of cmdstan

In [2]:
ProjDir = rel_path_d("..", "scripts", "08")
cd(ProjDir)

### snippet 5.1

In [3]:
d = CSV.read(rel_path("..", "data", "rugged.csv"), delim=';');
df = convert(DataFrame, d);

dcc = filter(row -> !(ismissing(row[:rgdppc_2000])), df)
dcc[:log_gdp] = log.(dcc[:rgdppc_2000])
dcc[:cont_africa] = Array{Float64}(convert(Array{Int}, dcc[:cont_africa]))

170-element Array{Float64,1}:
 1.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 1.0
 ⋮  
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 1.0
 1.0
 1.0

First 5 rows with data

In [4]:
first(dcc[[:rugged, :cont_africa, :log_gdp]], 5)

struct m_8_1_model{TY <: AbstractVector, TX <: AbstractMatrix}
    "Observations."
    y::TY
    "Covariates"
    X::TX
end

Make the type callable with the parameters *as a single argument*.

In [5]:
function (problem::m_8_1_model)(θ)
    @unpack y, X, = problem   # extract the data
    @unpack β, σ = θ            # works on the named tuple too
    ll = 0.0
    ll += logpdf(Normal(0, 100), X[1]) # a = X[1]
    ll += logpdf(Normal(0, 10), X[2]) # bR = X[2]
    ll += logpdf(Normal(0, 10), X[3]) # bA = X[3]
    ll += logpdf(Normal(0, 10), X[4]) # bAR = X[4]
    ll += logpdf(TDist(1.0), σ)
    ll += loglikelihood(Normal(0, σ), y .- X*β)
    ll
end

Instantiate the model with data and inits.

In [6]:
N = size(dcc, 1)
X = hcat(ones(N), dcc[:rugged], dcc[:cont_africa], dcc[:rugged].*dcc[:cont_africa]);
y = convert(Vector{Float64}, dcc[:log_gdp])
p = m_8_1_model(y, X);
p((β = [1.0, 2.0, 1.0, 2.0], σ = 1.0))

-2770.7279383721293

Write a function to return properly dimensioned transformation.

In [7]:
problem_transformation(p::m_8_1_model) =
    as((β = as(Array, size(p.X, 2)), σ = asℝ₊))
# Wrap the problem with a transformation, then use Flux for the gradient.
P = TransformedLogDensity(problem_transformation(p), p)
∇P = LogDensityRejectErrors(ADgradient(:ForwardDiff, P));

Tune and sample.

In [8]:
chain, NUTS_tuned = NUTS_init_tune_mcmc(∇P, 1000);

MCMC, adapting ϵ (75 steps)
0.00043 s/step ...done
MCMC, adapting ϵ (25 steps)
0.00036 s/step ...done
MCMC, adapting ϵ (50 steps)
0.0003 s/step ...done
MCMC, adapting ϵ (100 steps)
0.00029 s/step ...done
MCMC, adapting ϵ (200 steps)
0.00023 s/step ...done
MCMC, adapting ϵ (400 steps)
0.00024 s/step ...done
MCMC, adapting ϵ (50 steps)
0.00018 s/step ...done
MCMC (1000 steps)
0.00024 s/step ...done


We use the transformation to obtain the posterior from the chain.

In [9]:
posterior = TransformVariables.transform.(Ref(problem_transformation(p)), get_position.(chain));
posterior[1:5]

5-element Array{NamedTuple{(:β, :σ),Tuple{Array{Float64,1},Float64}},1}:
 (β = [9.311327097945934, -0.27398760060317157, -2.1021065053022463, 0.5378503861805575], σ = 0.9709625313276751)
 (β = [9.344803105739702, -0.28014007522597917, -2.3420634942751843, 0.6040347953417786], σ = 0.9895447476329379)
 (β = [9.075027139796676, -0.15085727397843413, -1.5520630646685698, 0.2193810937502221], σ = 0.8900236239969783)
 (β = [9.149148629964957, -0.14988456140665543, -2.004984256346308, 0.398902199995137], σ = 0.9597869852818984)  
 (β = [9.331789133338088, -0.25839585932752573, -1.8966397039358303, 0.345062798749551], σ = 0.900131663484713)  

Extract the parameter posterior means: `β`,

In [10]:
posterior_β = mean(first, posterior)

4-element Array{Float64,1}:
  9.227467740746324
 -0.205227569945205
 -1.959298548634326
  0.398479227625313

then `σ`:

In [11]:
posterior_σ = mean(last, posterior)

0.9486035918120415

Effective sample sizes (of untransformed draws)

In [12]:
ess = mapslices(effective_sample_size,
                get_position_matrix(chain); dims = 1)
# NUTS-specific statistics
NUTS_statistics(chain)

Hamiltonian Monte Carlo sample of length 1000
  acceptance rate mean: 0.81, min/25%/median/75%/max: 0.47 0.78 0.84 0.87 0.88
  termination: AdjacentTurn => 9% DoubledTurn => 91%
  depth: 1 => 0% 2 => 19% 3 => 81%


Result rethinking

In [13]:
rethinking = "
       mean   sd  5.5% 94.5% n_eff Rhat
a      9.22 0.14  9.00  9.46   282    1
bR    -0.21 0.08 -0.33 -0.08   275    1
bA    -1.94 0.24 -2.33 -1.59   268    1
bAR    0.40 0.14  0.18  0.62   271    1
sigma  0.96 0.05  0.87  1.04   339    1
"

"\n       mean   sd  5.5% 94.5% n_eff Rhat\na      9.22 0.14  9.00  9.46   282    1\nbR    -0.21 0.08 -0.33 -0.08   275    1\nbA    -1.94 0.24 -2.33 -1.59   268    1\nbAR    0.40 0.14  0.18  0.62   271    1\nsigma  0.96 0.05  0.87  1.04   339    1\n"

Summary

In [14]:
[posterior_β, posterior_σ]

2-element Array{Any,1}:
  [9.227467740746324, -0.205227569945205, -1.959298548634326, 0.398479227625313]
 0.9486035918120415                                                             

End of `08/m8.1s.jl`

*This notebook was generated using [Literate.jl](https://github.com/fredrikekre/Literate.jl).*