# Linear regression

In [1]:
using DynamicHMCModels

ProjDir = rel_path_d("..", "scripts", "05")
cd(ProjDir)

Import the dataset.

### snippet 5.1

In [2]:
wd = CSV.read(rel_path("..", "data", "WaffleDivorce.csv"), delim=';')
df = convert(DataFrame, wd);
mean_ma = mean(df[:MedianAgeMarriage])
df[:MedianAgeMarriage_s] = convert(Vector{Float64},
  (df[:MedianAgeMarriage]) .- mean_ma)/std(df[:MedianAgeMarriage]);
# Show the first six rows of the dataset.
first(df, 6)

6×14 DataFrame. Omitted printing of 9 columns
│ Row │ Location   │ Loc     │ Population │ MedianAgeMarriage │ Marriage │
│     │ String⍰    │ String⍰ │ Float64⍰   │ Float64⍰          │ Float64⍰ │
├─────┼────────────┼─────────┼────────────┼───────────────────┼──────────┤
│ 1   │ Alabama    │ AL      │ 4.78       │ 25.3              │ 20.2     │
│ 2   │ Alaska     │ AK      │ 0.71       │ 25.2              │ 26.0     │
│ 3   │ Arizona    │ AZ      │ 6.33       │ 25.8              │ 20.3     │
│ 4   │ Arkansas   │ AR      │ 2.92       │ 24.3              │ 26.4     │
│ 5   │ California │ CA      │ 37.25      │ 26.8              │ 19.1     │
│ 6   │ Colorado   │ CO      │ 5.03       │ 25.7              │ 23.5     │

Model ``y ∼ Normal(y - Xβ, σ)``. Flat prior for `β`, half-T for `σ`.

In [3]:
struct WaffleDivorceProblem{TY <: AbstractVector, TX <: AbstractMatrix}
    "Observations."
    y::TY
    "Covariates"
    X::TX
end

Make the type callable with the parameters *as a single argument*.

In [4]:
function (problem::WaffleDivorceProblem)(θ)
    @unpack y, X, = problem   # extract the data
    @unpack β, σ = θ            # works on the named tuple too
    ll = 0.0
    ll += logpdf(Normal(10, 10), X[1]) # a = X[1]
    ll += logpdf(Normal(0, 1), X[2]) # b1 = X[2]
    ll += logpdf(TDist(1.0), σ)
    ll += loglikelihood(Normal(0, σ), y .- X*β)
    ll
end

Instantiate the model with data and inits.

In [5]:
N = size(df, 1)
X = hcat(ones(N), df[:MedianAgeMarriage_s]);
y = convert(Vector{Float64}, df[:Divorce])
p = WaffleDivorceProblem(y, X);
p((β = [1.0, 2.0], σ = 1.0))

-2225.6614871340917

Write a function to return properly dimensioned transformation.

In [6]:
problem_transformation(p::WaffleDivorceProblem) =
    as((β = as(Array, size(p.X, 2)), σ = asℝ₊))
# Wrap the problem with a transformation, then use Flux for the gradient.
P = TransformedLogDensity(problem_transformation(p), p)
∇P = LogDensityRejectErrors(ADgradient(:ForwardDiff, P));

Tune and sample.

In [7]:
chain, NUTS_tuned = NUTS_init_tune_mcmc(∇P, 1000);

MCMC, adapting ϵ (75 steps)
0.00017 s/step ...done
MCMC, adapting ϵ (25 steps)
4.2e-5 s/step ...done
MCMC, adapting ϵ (50 steps)
5.1e-5 s/step ...done
MCMC, adapting ϵ (100 steps)
0.00011 s/step ...done
MCMC, adapting ϵ (200 steps)
2.6e-5 s/step ...done
MCMC, adapting ϵ (400 steps)
3.8e-5 s/step ...done
MCMC, adapting ϵ (50 steps)
3.0e-5 s/step ...done
MCMC (1000 steps)
4.6e-5 s/step ...done


We use the transformation to obtain the posterior from the chain.

In [8]:
posterior = TransformVariables.transform.(Ref(problem_transformation(p)), get_position.(chain));
posterior[1:5]

5-element Array{NamedTuple{(:β, :σ),Tuple{Array{Float64,1},Float64}},1}:
 (β = [9.685938710371099, -1.1178831535256994], σ = 1.1695133962200455) 
 (β = [9.592811910321435, -1.0722697976581759], σ = 1.6807620332447264) 
 (β = [9.59386086635352, -0.8279457342286715], σ = 1.1939660266466912)  
 (β = [10.083894973958387, -1.3164785698507826], σ = 1.5855673372439405)
 (β = [9.939911137100019, -1.3571319906986585], σ = 1.5172117829676923) 

Extract the parameter posterior means: `β`,

In [9]:
posterior_β = mean(first, posterior)

2-element Array{Float64,1}:
  9.701011684454333
 -1.099849105068532

then `σ`:

In [10]:
posterior_σ = mean(last, posterior)

1.487458307289001

Effective sample sizes (of untransformed draws)

In [11]:
ess = mapslices(effective_sample_size,
                get_position_matrix(chain); dims = 1)
# NUTS-specific statistics
NUTS_statistics(chain)

Hamiltonian Monte Carlo sample of length 1000
  acceptance rate mean: 0.9, min/25%/median/75%/max: 0.09 0.85 0.94 0.99 1.0
  termination: AdjacentTurn => 31% DoubledTurn => 69%
  depth: 1 => 6% 2 => 65% 3 => 18% 4 => 8% 5 => 3% 6 => 0%


cmdstan result

In [12]:
cmdstan_result = "
Iterations = 1:1000
Thinning interval = 1
Chains = 1,2,3,4
Samples per chain = 1000

Empirical Posterior Estimates:
         Mean        SD       Naive SE       MCSE      ESS
    a  9.6882466 0.22179190 0.0035068378 0.0031243061 1000
   bA -1.0361742 0.21650514 0.0034232469 0.0034433245 1000
sigma  1.5180337 0.15992781 0.0025286807 0.0026279593 1000

Quantiles:
         2.5%      25.0%     50.0%      75.0%       97.5%
    a  9.253141  9.5393175  9.689585  9.84221500 10.11121000
   bA -1.454571 -1.1821025 -1.033065 -0.89366925 -0.61711705
sigma  1.241496  1.4079225  1.504790  1.61630750  1.86642750
";

Extract the parameter posterior means: `β`,

In [13]:
[posterior_β[1], posterior_β[2], posterior_σ]

3-element Array{Float64,1}:
  9.701011684454333
 -1.099849105068532
  1.487458307289001

end of m4.5d.jl#-
*This notebook was generated using [Literate.jl](https://github.com/fredrikekre/Literate.jl).*